apiVersion: apps/v1
kind: Deployment
metadata:
  name: srbrianrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srbrianrs
  template:
    metadata:
      labels:
        app: srbrianrs
    spec:
      containers:
      - image: okteto.dev/srbrianrs:latest
        name: srbrianrs
        envFrom:
        - configMapRef:
            name: srbrianrs-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: srbrianrs
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "srbrianrs"
    port: 8080
  selector:
    app: srbrianrs