# Generated by Django 3.1.3 on 2023-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(default='')),
                ('model', models.TextField(default='')),
                ('color', models.TextField(default='')),
                ('version', models.TextField(default='')),
                ('year', models.IntegerField()),
                ('engine', models.TextField(default='')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('airbags', models.BooleanField()),
                ('absbreak', models.BooleanField()),
            ],
        ),
    ]
