name: release CI/CD

#Controls when the action will run.
on:

  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix: 
        python-version: [3.8]
